all:
  children:
    lb:
      hosts:
        load_balancer:
          ansible_host: 192.168.56.151
          ansible_ssh_user: vagrant
          ansible_python_interpreter: /usr/bin/python3
    apps:
      hosts:
        app1:
          ansible_host: 192.168.56.152
          ansible_ssh_user: vagrant
          ansible_python_interpreter: /usr/bin/python3
        app2:
          ansible_host: 192.168.56.153
          ansible_ssh_user: vagrant
          ansible_python_interpreter: /usr/bin/python3
    db:
      hosts:
        database:
          ansible_host: 192.168.56.154
          ansible_ssh_user: vagrant
          ansible_python_interpreter: /usr/bin/python3