Vagrant.configure("2") do |config|
  controller_node = { name: "controller", memory: 1024, cpus: 1, ip: "192.168.56.150", box: "bento/ubuntu-22.04" }
  managed_nodes = [
    { name: "lb", memory: 2048, cpus: 2, ip: "192.168.56.151", box: "bento/ubuntu-22.04" },
    { name: "app1", memory: 1024, cpus: 1, ip: "192.168.56.152", box: "bento/ubuntu-22.04" },
    { name: "app2", memory: 1024, cpus: 1, ip: "192.168.56.153", box: "bento/ubuntu-22.04" },
    { name: "db", memory: 2048, cpus: 2, ip: "192.168.56.154", box: "bento/ubuntu-22.04" }
  ]

  config.vm.synced_folder "data", "/home/vagrant/data"

  config.vm.define controller_node[:name] do |machine|
    machine.vm.box = controller_node[:box]
    machine.vm.hostname = controller_node[:name]
    machine.vm.provider "virtualbox" do |vb|
      vb.memory = controller_node[:memory]
      vb.cpus = controller_node[:cpus]
    end
    machine.vm.network "private_network", ip: controller_node[:ip]

    machine.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo apt install -y htop python3 python3-pip software-properties-common
      sudo add-apt-repository --yes --update ppa:ansible/ansible
      sudo apt install -y ansible

      mkdir -p /home/vagrant/.ssh
      chmod 700 /home/vagrant/.ssh

      if [ ! -f /home/vagrant/.ssh/id_rsa ]; then
        ssh-keygen -t rsa -b 4096 -f /home/vagrant/.ssh/id_rsa -N ""
      fi

      chmod 600 /home/vagrant/.ssh/id_rsa
      chown vagrant:vagrant /home/vagrant/.ssh/id_rsa

      cp /home/vagrant/.ssh/id_rsa.pub /home/vagrant/data/controller_id_rsa.pub
    SHELL
  end

  managed_nodes.each do |node|
    config.vm.define node[:name] do |machine|
      machine.vm.box = node[:box]
      machine.vm.hostname = node[:name]
      machine.vm.provider "virtualbox" do |vb|
        vb.memory = node[:memory]
        vb.cpus = node[:cpus]
      end
      machine.vm.network "private_network", ip: node[:ip]

      machine.vm.provision "shell", inline: <<-SHELL
        sudo apt update
        sudo apt install -y htop python3 python3-pip

        while [ ! -f /home/vagrant/data/controller_id_rsa.pub ]; do
          echo "Error: Controller Public key not found!!"
        done

        cat /home/vagrant/data/controller_id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
        chmod 700 /home/vagrant/.ssh
        chmod 600 /home/vagrant/.ssh/authorized_keys
        chown -R vagrant:vagrant /home/vagrant/.ssh
      SHELL
    end
  end
end
